### ISSUE TITLE
Remove mocha-as-promised/chai-as-promised require lines

### ISSUE THREAD

**Issue by kevinburkeshyp** [goshippo/shippo-node-client#13]
The tests run just fine without them. It would also be nice if you added mocha and chai as dev dependencies in your package.json.

**Comment by mnowik** [comment]
Hi @kevinburkeshyp, thanks for creating the issues and sorry for our delay. I am going to close this issue, it was fixed with this commit 8199d01. I will take care of the other issues in the next weeks
