### ISSUE TITLE
question: is there are way to do multi-parcel shipments ?

### ISSUE THREAD

**Issue by gaboesquivel** [goshippo/shippo-node-client#17]
Is it possible to make multi-parcel shipments using shippo-node-client?
I'm currently working on an app the needs to guarantee multiple parcels are delivered together on the same date and have the ability to track them as a single service request.

**Comment by simonkreuz** [comment]
To group & track multiple packages as one shipment you can use the `reference_1` and `reference_2` fields of the Shipment object. Just set them to the same shipment or invoice ID, and FedEx, UPS and DHL will allow you to track all packages with this ID. 

We'll add support for adding multiple parcels to one shipment, which would automatically take care of this. We expect this to be released in Q2 this year.

**Comment by gaboesquivel** [comment]
awesome, thanks and happy holidays!

**Comment by gaboesquivel** [comment]
@simonkreuz will this create a [Fedex MPS] ?(https://www.fedex.com/us/developer/WebHelp/fsms/1401/dvg/DVG-WebHelp/2_7_2_Multiple_Piece.htm)

**Comment by simonkreuz** [comment]
Using `reference_1` and `reference_2` does not create a MPS, but the new feature that we're working on will support it.

**Comment by andrest** [comment]
@simonkreuz how far along is the feature?

**Comment by mirabaiapplegate** [comment]
@andrest We'll be rolling out MPS for both FedEx and UPS in the next few weeks!

**Comment by andrest** [comment]
@mirabaiapplegate wonderful news, do let us know when that happens.

**Comment by mirabaiapplegate** [comment]
@andrest Will do!

**Comment by mirabaiapplegate** [comment]
@andrest We'd love to have you Beta test! Send me an email at mirabai@goshippo.com, and I'll be in touch!
