### ISSUE TITLE
Tracking Calls

### ISSUE THREAD

**Issue by kennetpostigo** [goshippo/shippo-node-client#27]
Hello, 

I went through a bit of the API Reference and Guides and couldn't find what API method to use for checking the Tracking Status. Also briefly skimmed through the source code and couldn't find anything related to tracking. Can you tell me what `shippo.[insert trackingCall](...)` to fetch tracking status of shipments.

**Comment by simonkreuz** [comment]
Hi @kennetpostigo! Unfortunately the Tracking Status endpoint (https://goshippo.com/docs/reference#tracks) is not yet supported in this client library. Our team will be working on it soon but there is no clear timeline yet. I'm sorry that I don't have a better answer for you!

**Comment by kennetpostigo** [comment]
Alrighty

**Comment by kennetpostigo** [comment]
Anything I can do to help?

**Comment by simonkreuz** [comment]
If you would like to contribute we'd love to check out your changes in a PR and merge them. Of course this is something that our team is committed to doing on our end, but if you have the chance to extend the wrapper in the meantime we'd definitely love to built on top of your code.

Also, if you have any questions about the use cases / API calls I'm very happy to help! :)

**Comment by kennetpostigo** [comment]
@simonkreuz awesome, would like to help out. Going to read the source code some more before I send in a PR.

**Comment by simonkreuz** [comment]
Awesome, thanks @kennetpostigo! Feel free to reach out here or at simon@goshippo.com if you have any questions. Jason (from the other issue) can also help.

**Comment by kennetpostigo** [comment]
@simonkreuz will do :)
