### ISSUE TITLE
All methods promise based?

### ISSUE THREAD

**Issue by kennetpostigo** [goshippo/shippo-node-client#28]
Hey,

Just wondering if all API methods return promise promises that we can `.then()` and `.catch()` on?

**Comment by smithjason** [comment]
The `shippo-node-client` uses When and uses its `when.defer()` when making API requests.

You can see the relevant documentation for how to use this here: [when.defer documentation](https://github.com/cujojs/when/blob/master/docs/api.md#whendefer)

**Comment by kennetpostigo** [comment]
@smithjason why not use standard JS promises? They're supported by node and removes `when` dependency.

**Comment by kennetpostigo** [comment]
Because running the following:
```js
function createShipment (req, res) {
  return shippo.shipment.create({
    "object_purpose": "PURCHASE",
    "address_from": addressFrom,
    "address_to": addressTo,
    parcel: parcel
  })
  .then(response => {
    console.log(response);
    res.send(response);
  })
  .catch(err => console.log('Error: ', err));
}
```

returns this error:
```error
TypeError: _shippo2.default.shipment.create(...).then(...).catch is not a function
```

**Comment by kennetpostigo** [comment]
I was going through the repo and this is the only portion of the codebase I was able to find that uses `when` outside of tests.

As is:
```js
  createDeferred: function(callback) {
      var deferred = when.defer();

      if (callback) {
        // Callback, if provided, is a simply translated to Promise'esque:
        // (Ensure callback is called outside of promise stack)
        deferred.promise.then(function(res) {
          setTimeout(function(){ callback(null, res) }, 0);
        }, function(err) {
          setTimeout(function(){ callback(err, null); }, 0);
        });
      }

      return deferred;
  },
```

Please correct me if I'm wrong, from my understanding it takes in a callback, im assuming thats the second parameter of the API method calls. from there if there is a callback it wraps the callback in a `deffered` that you call `then` on  for some reason then theres a `setTImeout` call in there not sure why. Could you please explain that to me? If theres not a callback it returns a deferred, from which I guess the user could handle.

**Comment by kennetpostigo** [comment]
Especially with `async` functions just becoming standardized and part of spec as of a few days ago I think it's probably better to move away from when in order to take advantage of its benefit of making asynchronous work look synchronous, but more importantly the error handling that it enables. Seeing that `when`'s deffered doesn't have a `catch` method you would lose this.

**Comment by smithjason** [comment]
Correct.  Currently there are two options: 1) pass a callback as the last parameter of a Resource method call, or 2) chain a #then without passing the callback to the Resource method.  Yes, the fact that it wraps the callback in `setTimeout` is weird.  This is something I can add to our backlog for improvements.

**Comment by kennetpostigo** [comment]
@smithjason If you want I can rewrite that when portion to use Native JS Promises. I just want to understand what you want to do when a callback is passed and what you want to do when no call back is passed. From my understanding this is kind of something you want to do:

```js
// Here is a simple solution using native JavaScript Promises: 
createPromise: function (callback) {
  if (callback) {
    // wrap callback and return Promise thats thenable
    return Promise.resolve(callback())
  }
  // return a Promise thats thenable
  return Promise.resolve()
}
```

I hope this will do. If this looks okay to do I'm happy to do a pull request.
