### ISSUE TITLE
Address Creation Never Returns from a Promise

### ISSUE THREAD

**Issue by chris-patten-volusion** [goshippo/shippo-node-client#33]
When calling the following code it appears to never return a promise.  Create appears to be a promises but it never resolves...

Here is the code that I am using to duplicate the issue, replace with a correct shippo API key:

`let shippo = require('shippo');
shippo = shippo('****');

const createAddress = () => {
  console.log(`Address Creation Start`);
  const address = {
    name: 'Chris',
    street1: '602 Kai Dr',
    city: 'Cedar Park',
    state: 'TX',
    email: 'something@gmail.com',
    zipCode: '78613'
  };
  address.validate = true;
  address.async
  let test = shippo.address.create;
  console.log(test);
  var address2 = shippo.address.create(address);
  return address2
    .then(result => {
      console.log(`Address Creation: ${JSON.stringify(result)}`);
      if (result.object_state !== 'VALID') {
        console.log(`Error happened: ${result}`);
        const error = {
          statusCode: 400,
          message: result.messages[0].text
        };

        throw error;
      }

      console.log(`Success!`);
      return {isValid: true};
    });
};

promiseAddress = () => {
  console.log('Here now');
  return createAddress()
    .then(result => {
      console.log(`${JSON.stringify(result)}`);
    });
};

promiseAddress();`

**Comment by mootrichard** [comment]
You'll want to add a .catch() to your promise so that you could catch any errors that might arise in the event that the promise couldn't be returned (which is why its never returning here).

One of our developers was able to see that you need to supply a country with your request there. 

You can find a node example at [https://goshippo.com/docs/address-validation](https://goshippo.com/docs/address-validation) that shows an example of the information to provide when creating/validating an address.

**Comment by chris-patten-volusion** [comment]
Yes, I missed the country but the code about will still finish and not wait for the promise to resolve even without the country.  I removed the catch from my sample code because it throws a different error.  I added a catch and it tells me address.create().then().catch() is not a function.  Here is the code with a catch and country and it is still not working.  Was the developer able to run the code above with the country code and a catch and it worked because it is not working for me.

`let shippo = require('shippo');
shippo = shippo('***');

const createAddress = () => {
  console.log('Address Creation Start');
  const address = {
    name: 'Chris',
    street1: '602 Kai Dr',
    city: 'Cedar Park',
    state: 'TX',
    email: 'something@gmail.com',
    zipCode: '78613',
    country: 'US',
    validate: true
  };

  return shippo.address.create(address)
    .then(result => {
      console.log('Address Creation: ${JSON.stringify(result)}');

      console.log(`Success! ${JSON.stringify(result)}`);
      return {};
    }).
    catch(error => {
      console.log(`Error: ${JSON.stringify(error)}`);
    });

};

promiseAddress = () => {
  console.log('Here now');
  return createAddress()
    .then(result => {
      console.log(`${JSON.stringify(result)}`);
    }).
    catch(error => {
      console.log(`Error 2: ${error}`);
    });
};

promiseAddress();`

**Comment by mootrichard** [comment]
I had to modify the code a bit, since I wasn't sure if you were setting promiseAddress as a promise object prior to attempting to use .then() and .catch() (likely why you were getting the error that .catch() is not a function).

I have provided a modified version of what you wrote that works on returning a valid address back. If you remove 'country' from there, it will log out the catch with what the error is.
```
let shippo = require('shippo');
shippo = shippo('****');

const createAddress = () => {
	console.log('Address Creation Start');
	const address = {
		name: 'Chris',
		street1: '602 Kai Dr',
		city: 'Cedar Park',
		state: 'TX',
		country:'US',
		email: 'something@gmail.com',
		zipCode: '78613'
	};
	address.validate = true;
	address.async;
	let test = shippo.address.create;
	console.log(test);
	var address2 = shippo.address.create(address);
	return address2
	.then(result => {
		console.log(`Address Creation: ${JSON.stringify(result)}`);
		if (result.object_state !== 'VALID') {
			console.log(`Error happened: ${result}`);
			const error = {
				statusCode: 400,
				message: result.messages[0].text
			};
			throw error;
		}
		console.log('Success!');
		return {isValid: true};
	});
};

let promiseAddress = new Promise((resolve, reject)=>{
	resolve('Success');
	reject('Failure');
});

promiseAddress.then(createAddress).catch((e)=>{
	console.log(e);
});
```

Let me know if that works for you or not.

**Comment by chris-patten-volusion** [comment]
I understand the solution to the problem.  That is actually what I did to work around the issues.  I guess what I was trying to get at is why is this package mixed promises and callbacks?  On other calls I had a property called 'async' that turned the calls into promise (Shipping and Transaction Resource).  On other resources such as Rate, it appears to default to a promise, with no 'async' flag. Then it looks like Address is default to return a callback with no 'async' flag to change it.  It would be nice if that same functionality was available on every resource. I am currently not blocked and working around it.  Sorry for the confusion.
