### ISSUE TITLE
Webhooks Not Sending Request

### ISSUE THREAD

**Issue by 0807Jpatel** [goshippo/shippo-node-client#35]
I have waited for more than 2 hours but I never get a request from webhook saying status has changed. but when I got to api.../track/carrier/tracknumber it will send a request right away.

**Comment by 0807Jpatel** [comment]
Seems like webhook are updating but not every two hours it takes them longer to send messages out.

**Comment by mootrichard** [comment]
When it comes to webhooks, we _poll_ the carrier every 2 hours. If find that the package's status has changed, we push the update immediately. [Webooks docs](https://goshippo.com/docs/webhooks)

So, although you might have POSTed a tracking number to your Shippo account, if we haven't found any change in the status, you wouldn't get anything sent to your webhook. This also means that if we just polled the carrier, and your package's status changed shortly after the poll, it would be ~2 hours until then next poll that you would get the update pushed to your webhook.

If this is not the behavior that you're experiencing, please leave a little more info so that I can track down what is happening with your account to get more info to you.

**Comment by mootrichard** [comment]
One other thing, did you do a GET on that tracking number prior to doing a POST on the same tracking number?

**Comment by 0807Jpatel** [comment]
Hey, so I check lasership it updated its status on a package I was tracking at 12:37 am and I didn't get webhook post till 3:36 am so there was more than two hour gap.  All I am doing is once I get the tracking number and carrier name, I make a webhook json object and shippo.track.create(webhook json obj).

**Comment by mootrichard** [comment]
When had you originally posted your tracking number? I had looked through our logs, and as far as I could tell, you had POSTed a tracking number around 02:23 UTC. That same shipment had a new status at 08:37UTC (when we picked it up). We had pushed this update to you at that time.

One thing to note, is that each carrier handles the timestamps on tracking differently. It appears that LaserShip is giving local timestamps for their shipments on the one that I was looking at (not UTC times). So the status at 12:45AM (EST) would be 5:45 UTC. 

One other thing, is that we would only be able to push out the data once it is available. Even though the status is logged at a certain time, that doesn't necessarily mean that the status update is available to access. Not all carriers update the status of their packages in real-time (there might be a slight delay before you could get an update). So it might mean they scanned it at 12:45AM, but didn't make that update available until much later than that.

**Comment by 0807Jpatel** [comment]
01/29 5:00 pm	LaserShip Origin Scan            ---> I added webhook and get info at 1/29 9:36 pm
01/30 2:45 am	Arrived at LaserShip Facility   ---> I got post on webhook at 1/30 3:36 am
01/30 8:57 am	Loaded onto vehicle               
01/30 8:57 am	Out for Delivery                       ---> I got post at 1/30 9:36 am
01/304:39 pm	Left at Front Door                   ---> I got post at 1/30 9:36 pm

I am in newyork so lasership time should match with my time (EST), so I got update for the out of delivery within an hour, so I think the api is def updating within an hour for public. and it took almost 5 hours to get the information about Left at front door which I dont understand.

**Comment by mootrichard** [comment]
In digging into this further with our team, I was able to find that the polling time can be in the range of 2 to 5 hours (not just the 2 hours that is listed there). 

We will be looking into how often this polls and also update documentation to be more reflective of the actual polling intervals.

**Comment by 0807Jpatel** [comment]
Thank you for the update. One more question do u guys have the api as open source? or on github for me to take a look at it? is there an option to look at it?

**Comment by mootrichard** [comment]
The API is not open source or on GitHub. Only our API client libraries are open source. You're always welcome to take a look at our documentation over at [Shippo Docs](https://goshippo.com/docs/references) [Shippo References](https://goshippo.com/docs/references)

**Comment by harishvc** [comment]
👍
