### ISSUE TITLE
FedEx API is not responding

### ISSUE THREAD

**Issue by nnpatel** [goshippo/shippo-node-client#44]
Sometimes while fetching the rates api is not responding.

As a response I got

messages: 
   [ { source: 'FedEx',
       code: '',
       text: 'FedEx API did not respond. Please try again in a few minutes.' } ],

And if I try after few seconds or a minute, I got the response.

Any suggestion for it?

**Comment by vvkaghera** [comment]
Any solutions? Got same error

`{"source":"FedEx","code":"","text":"FedEx API did not respond. Please try again in a few minutes."}
`

**Comment by jato** [comment]
If the request was made using 'test' credentials, it has a higher chance of timing out. Unfortunately, the FedEx response time is much longer when their test servers are being used. As a workaround, you could poll for rates using your 'live' credentials; their production servers have a much better response rate. (Note: FedEx labels are scan-based and not invoiced until scanned)

**Comment by jhoanborges** [comment]
same
