### ISSUE TITLE
ES6 Imports

### ISSUE THREAD

**Issue by bzmillerboy** [goshippo/shippo-node-client#49]
I'm using TS and ES6 imports with the following:

```
import * as Shippo from 'shippo';
const shippo = new Shippo('<YOUR_PRIVATE_KEY>');

```

However, I continue to get 400 response with "Invalid credentials". I've triple checked my credentials. Is this this the proper way to import and set the key with ES6.

*Obviously, I've replaced `<YOUR_PRIVATE_KEY>` with my actual key.

**Comment by bzmillerboy** [comment]
I've resolved by using this code in my config.ts instead of my helper.ts file.

**Comment by acomito** [comment]
hmm... I'm getting "Shippo is not a constructor"
