### ISSUE TITLE
Transaction list returns null for multi-piece shipments

### ISSUE THREAD

**Issue by becauseinterwebs** [goshippo/shippo-node-client#64]
After creating a label transaction for a multi-piece shipment with a rate object_id, I am calling shippo.transactions.list with the rate object_id to get the additional labels, but it always returns null.  I have also tried it using the object_id returned in the transaction.  I get the first label as normal when the transaction is created.

I also tried it on curl and get the same result:

`https://api.goshippo.com/transactions/?rate=<rate object_id>  -H "Authorization: ShippoToken shippo_test_xxxxxxxxxxxxxxxxxx"`

Does this not work in test mode or am I not using the right object_id?

Thank you!

**Comment by jfriedr** [comment]
Hey @becauseinterwebs sorry this got missed.  I just saw this message in your zendesk ticket.  

You cannot use test and production tokens interchangeably.

Let me know if you have any other questions.

**Comment by becauseinterwebs** [comment]
I don't think I've done any live API calls.  So far everything has been in test mode.

**Comment by jfriedr** [comment]
Thanks, I was able to confirm that.  

Just to confirm you ran this curl and got no results?

`curl -H"Authorization: ShippoToken shippo_test_XXXXXXXXXXXX" --url "https://api.goshippo.com/transactions/?results=15&rate=2f2c54bdfa70439d89aa9b563dd9ac3e"`

**Comment by becauseinterwebs** [comment]
Hey Joseph,

I am using the NodeJS SDK, but also tried it using curl as you have
provided above.  I've tried it the the "rate" field returned from creating
a label as well as the object_id field, thinking maybe I was passing in the
wrong id.  I could not pull them in either the SKD or using curl, but the
main label that comes back says "1 of 2."

- Brent
