### ISSUE TITLE
[Feature Request] Get parcel templates

### ISSUE THREAD

**Issue by khacminh** [goshippo/shippo-node-client#73]
Currently, I cannot get the parcel templates created on my account. A workaround is I have to store them locally and update the template list manually. There is an issue reported on php library since 2016 (and closed). Please put this feature back to live

https://github.com/goshippo/shippo-php-client/issues/28

**Comment by jfriedr** [comment]
@khacminh this was just recently added. 

https://goshippo.com/docs/reference#user-parcel-templates

**Comment by khacminh** [comment]
Hi @jfriedr 

Thank you for your update.

I see that there are 3 redundant fields as image below:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/13713865/160040923-2b4a752f-aaa2-4938-9ec6-a6b2386fb72b.png">

**Comment by jfriedr** [comment]
@khacminh Is it redundant? If the user doesn't have the details saved in their original request then where else would it be displayed?  Are you saying it would be in the package details in a rate/shipment request? If I'm missing something please let me know.

**Comment by khacminh** [comment]
@jfriedr 

In the API document:
- `distanceUnit` is provided as `distance_unit`
- `massUnit` is provided as `weight_unit `
- `id` is provided as `object_id `

In the real response payload, I see that besides the provided fields, these fields were added without being mentioned in the document.


<img width="518" alt="image" src="https://user-images.githubusercontent.com/13713865/160248308-2c21d7e2-5d5f-4410-ae4f-89f1983c88bf.png">
